age = input("Please tell me your age: ")
print("You are currently " + age + " years old.")
print("In 10 years, you will be " + str(int(age) + 10) + " years old.")
print("In 20 years, you will be " + str(int(age) + 20) + " years old.")
print("In 30 years, you will be " + str(int(age) + 30) + " years old.")